# Generated by Django 4.2.20 on 2025-04-30 20:26

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.movie_image_file_path
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.movie_image_file_path
            ),
        ),
    ]
